### ISSUE TITLE
Preprocessing the Input Image

### ISSUE THREAD

**Issue by GodOfProbability** [raghakot/keras-vis#17]
I observed in the examples that the seed images are not preprocessed by subtracting the mean, as it is required in the VGG-Net. I am sure the activation in the end of the of the model will be different if don't subtract the mean from the input image. Am I missing something?

**Comment by pGit1** [comment]
Biggest weakness of this in my opinion.

**Comment by raghakot** [comment]
You can preprocess. I tried to keep the examples simple. The activations are similar-ish even if we don't subtract the mean. 

The examples are to illustrate the idea so that you can use it in your own projects. You would naturally preprocess image or run your pipelines steps according to your pipeline setup.
