### ISSUE TITLE
from vis.visualization import visualize_cam, overlay failing

### ISSUE THREAD

**Issue by amitkayal** [raghakot/keras-vis#182]
I am trying to import this module (from vis.visualization import visualize_cam, overlay
) from google colab and facing following error.
Looks like, that the module is referring old package which is no longer available?
Error:
Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c97826fd5ddd> in <module>()
      1 import matplotlib.cm as cm
----> 2 from vis.visualization import visualize_cam, overlay
      3 from keras import activations

1 frames
/usr/local/lib/python3.6/dist-packages/vis/visualization/saliency.py in <module>()
      3 import numpy as np
      4 import matplotlib.cm as cm
----> 5 from scipy.misc import imresize
      6 
      7 from keras.layers.convolutional import _Conv

ImportError: cannot import name 'imresize'

**Comment by keisen** [comment]
Unfortunately, `scipy.misc.imresize` have been removed since `scipy==1.3.0` .
We are going to fix this problem.
But for now, I believe that you can run following to avoid it:

```
pip install -I scipy==1.2.*
```

**Comment by sourcecode369** [comment]
> Unfortunately, `scipy.misc.imresize` have been removed since `scipy==1.3.0` .
> We are going to fix this problem.
> But for now, I believe that you can run following to avoid it:
> 
> ```
> pip install -I scipy==1.2.*
> ```

Thanks this really worked for me.

**Comment by bersbersbers** [comment]
Another fix: cherry-pick https://github.com/raghakot/keras-vis/commit/39e775b65c8fe89a86eaf3ea686db677de9990b2

```
git clone --branch=0.4.1 https://github.com/raghakot/keras-vis.git
cd keras-vis/
git cherry-pick 39e775
pip install .
```

**Comment by GopinathAchuthan** [comment]
After using this command,
pip install -I scipy==1.2.*

I am getting a different error.
         5 from scipy.misc import imresize
         6 
----> 7 from keras.layers.convolutional import _Conv
         8 from keras.layers.pooling import _Pooling1D, _Pooling2D, _Pooling3D
         9 from keras import backend as K

ImportError: cannot import name '_Conv'

**Comment by bersbersbers** [comment]
@GopinathRock you are describing #228. Note that this project is no longer maintained, consider using alternatives instead.

**Comment by ind-kum** [comment]
i am facing this error anyone can help me




from vis.visualization import visualize_activation
from vis.utils import utils
from keras import activations
from matplotlib import pyplot as plt
%matplotlib inline

plt.rcParams['figure.figsize'] = (18, 6)

# Utility to search for layer index by name
# Alternatively we can specify this as -1 since it corresponds to the last layer.
layer_idx = utils.find_layer_idx(model, 'preds')

# Swap softmax with linear
from keras import activations
model.layers[layer_idx].activation = activations.linear
model = utils.apply_modifications(model)

# This is the output node we want to maximize
filter_idx = 0
img = visualize_activation(model, layer_idx, filter_indices=filter_idx)

error------------------

ImportError                               Traceback (most recent call last)
<ipython-input-31-0c4a30aff6f0> in <module>()
----> 1 from vis.visualization import visualize_activation
      2 from vis.utils import utils
      3 from keras import activations
      4 from matplotlib import pyplot as plt
      5 get_ipython().magic('matplotlib inline')

1 frames
/usr/local/lib/python3.7/dist-packages/vis/visualization/saliency.py in <module>()
      3 import numpy as np
      4 import matplotlib.cm as cm
----> 5 from scipy.misc import imresize
      6 
      7 from keras.layers.convolutional import _Conv

ImportError: cannot import name 'imresize' from 'scipy.misc' (/usr/local/lib/python3.7/dist-packages/scipy/misc/__init__.py)
