### ISSUE TITLE
error and weird results when using visualize_cam

### ISSUE THREAD

**Issue by kirk86** [raghakot/keras-vis#27]
Hi,
I am getting the following error when I use `visualize_cam`:

```
Traceback (most recent call last):
  File "visual.py", line 60, in <module>
    heatmap = visualize_cam(model, layer_idx, [pred_class], img)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/vis/visualization.py", line 243, in visualize_cam
    _, grads, penultimate_output_value = opt.minimize(seed_img, max_iter=1, verbose=False)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/vis/optimizer.py", line 127, in minimize
    computed_values = self.compute_fn([seed_img, 0])
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2229, in __call__
    feed_dict=feed_dict)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/user/anaconda2/envs/adv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 933, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a int into a Tensor.
```

Here's the reproducible code example:

```
import numpy as np
import matplotlib.pyplot as plt
from keras import backend as K
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Model
from keras.layers import Conv2D, Dropout, Flatten, Dense, Input
# from vis.utils import utils
from vis.visualization import visualize_cam


K.set_learning_phase(0)


def create_model(data_shape):
    inpt = Input(shape=data_shape)
    x = Dropout(0.2, input_shape=data_shape)(inpt)
    x = Conv2D(64, (8, 8), strides=(2, 2),
               padding='same', activation='relu', input_shape=data_shape)(x)
    x = Conv2D((128), (6, 6), strides=(2, 2),
               padding='valid', activation='relu')(x)
    x = Conv2D((128), (5, 5), strides=(1, 1),
               padding='valid', activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Flatten()(x)
    x = Dense(10, activation='softmax')(x)
    model = Model(inpt, x, name='can_model_mine')
    model.compile(optimizer='adam', loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


if __name__ == "__main__":
    (trX, trY), (teX, teY) = mnist.load_data()
    trX = np.expand_dims(trX, axis=3)
    teX = np.expand_dims(teX, axis=3)
    trY = np_utils.to_categorical(trY, 10)
    teY = np_utils.to_categorical(teY, 10)
    model = create_model(trX.shape[1:])
    model.summary()
    model.fit(trX, trY, validation_split=0.21, batch_size=128, epochs=2,
              verbose=1)
    # plot original image
    img_idx = np.random.randint(0, 47400)
    img = trX[img_idx]
    # plt.imshow(img.reshape(28, 28))
    # plt.show()
    img = np.expand_dims(img, axis=0)
    print("image shape = {}".format(img.shape))

    # predicted and true class
    pred_class = np.argmax(model.predict(img))
    actual_class = np.argmax(trY[img_idx])
    print("predicted class = {}, true class = {}".format(pred_class,
                                                         actual_class))
    layer_name = 'dense_1'
    layer_idx = [idx for idx, layer in enumerate(model.layers)
                 if layer.name == layer_name][0]
    heatmap = visualize_cam(model, layer_idx, [pred_class], img)
    print("heatmap = {}".format(heatmap.shape))
    plt.axis('off')
    plt.imshow(heatmap.reshape(28, 28, 3))
    plt.title('Saliency map')
    plt.show()
```

If I remove `K.set_learning_phase(0)` I get the following weird results
![cam](https://cloud.githubusercontent.com/assets/2902390/26101925/d56225dc-3a2a-11e7-8f80-1cd6445edc66.png)

The thing is that I cannot remove `K.set_learning_phase(0)` since it is required by some other library that I'm using in my project.

Also some other times I get  the following error:

```
(Pdb) heatmap = visualize_cam(model, 6, [pred_class], np.expand_dims(img, axis=0))
Working on filters: [7]
*** AttributeError: Layer cnn_model_mine has multiple inbound nodes, hence the notion of "layer input" is ill-defined. Use `get_input_at(node_index)` instead.
```

**Comment by raghakot** [comment]
There are a couple of things going on there.

1. The reason ```visualize_cam``` output is bad because the penultimate conv layer have an output shape of (1, 1, 128). So we are essentially only getting (1, 1) output for weights. Try using the conv layer before that which has (5, 5) image resolution. You can do so by setting ```penultimate_layer_idx=3 or 2```. By default, it picks the lowest conv layer which has too small of an output resolution.

2. Even after I set a higher penultimate layer, the output was a constant heatmap, but that was because of a numerical issue. Essentially with small grad values, the computation is overflowing float32 precision and turning into zeros, effectively wiping out the heatmap information. since heatmap is initialized with all 1's you are seeing that red output everywhere. I just pushed a commit to fix that.

3. K.set_learning_phase(0) on the top, is a keras weirdness. Keras maintains an internal dictionary of various learning phases in a model graph (for example dropout) during construction time. By setting it ahead of model construction, you are also messing up your own model. to see what i mean, set a beakpoint of k.learning_phase() within keras code to see how it gets triggered with and without that top line. I noticed that it doesnt register learning phase for second dropout which is odd. I will investigate further but it might be a keras bug. In either case, this is more of a keras issue and i am out of options on what i can do here. There might be some hacky workarounds but i wouldn't want to include it in the lib.

**Comment by raghakot** [comment]
Closing this per offline discussion on slack

**Comment by Metete** [comment]
I am also having this problem. When training the keras pre-trained model, I first set keras to inference mode by K.set_learning_phase(0) to load the pre-trained model and then set keras to training mode by K.set_learning_phase(1). Unfortunately, this weird implementation is recommended by keras.

When I want to visualize learnt features of the neural network I get the same error (Cannot interpret feed_dict key as Tensor: Can not convert a int into a Tensor.) Are there any news about this problem?
